WhatToWhere/Areas/Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WhatToWhere.Areas.Web.Controllers
{
    public class AdminController : Controller
    {
        // GET: Web/Admin
        public ActionResult Dashboard()
        {
            ViewBag.title = "Dashboard";
            return View();
        }
    }
}

WhatToWhere/Areas/Web/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WhatToWhere.Areas.APIServices.Models;
using WhereToWhere.Data;

namespace WhatToWhere.Areas.Web.Controllers
{
    public class QuizController : Controller
    {
        // GET: Web/Quiz
        public ActionResult Index()
        {
            using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
            {
                var data = _dbcontext.tbl_question.Include("tbl_answer").OrderByDescending(x => x.QueId).ToList();
                return View(data);
            }
        }

        public ActionResult NewQuestion(int? QueId)
        {
            tbl_question model = new tbl_question();
            if (QueId.HasValue && QueId.Value > 0)
            {
                using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
                {
                    model = _dbcontext.tbl_question.Include("tbl_answer").Where(x => x.QueId == QueId).FirstOrDefault();
                    if (model != null)
                    {
                        return View(model);
                    }
                    else
                    {
                        //data not found
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult SaveQuestion(QuestionModel model)
        {
            if (ModelState.IsValid)
            {
                using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
                {
                    if (model.QueId != 0)
                    {
                        var existsData = _dbcontext.tbl_question.Where(x => x.QueId == model.QueId).FirstOrDefault();
                        if (existsData == null)
                        {
                            return Json(new { issuccess = false, message = "Something weent wrong. Try again." }, JsonRequestBehavior.AllowGet);
                        }
                        existsData.Question = model.Question;
                        existsData.ChoiceType = model.ChoiceType;
                        existsData.IsImageQuestion = model.IsImageQuestion;
                        _dbcontext.SaveChanges();
                    }
                    else
                    {
                        tbl_question data = new tbl_question();
                        data.Question = model.Question;
                        data.ChoiceType = model.ChoiceType;
                        data.IsImageQuestion = model.IsImageQuestion;
                        _dbcontext.tbl_question.Add(data);
                        _dbcontext.SaveChanges();
                        model.QueId = data.QueId;
                    }
                }
                return Json(new { issuccess = true, QueId = model.QueId }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { issuccess = false, message = "Enter values for all fields" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult SaveAnswer(AnswerModel model)
        {
            if (ModelState.IsValid)
            {
                using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
                {
                    if (model.QueId != 0 && model.AnsId != 0)
                    {
                        var existsData = _dbcontext.tbl_answer.Where(x => x.QueId == model.QueId && x.AnsId == model.AnsId).FirstOrDefault();
                        if (existsData == null)
                        {
                            return Json(new { issuccess = false, message = "Something weent wrong. Try again." }, JsonRequestBehavior.AllowGet);
                        }
                        existsData.DisplayText = model.DisplayText;
                        existsData.Value = model.Value;

                        if (!string.IsNullOrEmpty(model.ImageString))
                        {
                            //remove existing image
                            string existingImage = existsData.ImagePath;
                            if (!string.IsNullOrEmpty(existingImage))
                            {
                                string fileName = Path.GetFileName(existingImage);
                                String path = System.Web.HttpContext.Current.Server.MapPath("~/Images/Quiz");
                                System.IO.File.Delete(path + "/" + fileName);
                            }
                            existsData.ImagePath = SaveImage(model.ImageString);
                        }

                        _dbcontext.SaveChanges();
                    }
                    else
                    {
                        tbl_answer data = new tbl_answer();
                        data.QueId = model.QueId;
                        data.DisplayText = model.DisplayText;
                        data.Value = model.Value;

                        if (!string.IsNullOrEmpty(model.ImageString))
                        {
                            data.ImagePath = SaveImage(model.ImageString);
                        }

                        _dbcontext.tbl_answer.Add(data);
                        _dbcontext.SaveChanges();
                        model.AnsId = data.AnsId;
                    }
                }
                return Json(new { issuccess = true, AnsId = model.AnsId }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { issuccess = false, message = "Enter values for all fields" }, JsonRequestBehavior.AllowGet);
            }
        }

        private string SaveImage(string ImageString)
        {
            string ImgName = Guid.NewGuid().ToString();

            //Image image = Base64ToImage(Image.base64Image);
            String path = System.Web.HttpContext.Current.Server.MapPath("~/Images/Quiz"); //Path                                                                                                                     
            if (!System.IO.Directory.Exists(path))
            {
                System.IO.Directory.CreateDirectory(path);
            }
            string imageName = ImgName + ".jpg";
            //set the image path
            string imgPath = Path.Combine(path, imageName);
            if (ImageString.Contains("data:image"))
            {
                //Need To remove some header information at the beginning if image data contains
                //ImageDataUrl = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD....";
                //Otherwise, this will give an error.
                //Remove everything in front of the DataUrl and including the first comma.
                //ImageDataUrl = "9j/4AAQSkZJRgABAQAAAQABAAD...
                ImageString = ImageString.Substring(ImageString.LastIndexOf(',') + 1);
                // removing extra header information 
            }
            byte[] imageBytes = Convert.FromBase64String(ImageString);
            MemoryStream ms = new MemoryStream(imageBytes, 0, imageBytes.Length);
            ms.Write(imageBytes, 0, imageBytes.Length);
            System.Drawing.Image image = System.Drawing.Image.FromStream(ms, true);
            image.Save(imgPath, System.Drawing.Imaging.ImageFormat.Jpeg);
            return "http://www.whattowhere.net/Images/Quiz/" + imageName;
        }

        [HttpDelete]
        public JsonResult DeleteAnswer(int AnsId)
        {
            using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
            {
                if (AnsId > 0)
                {
                    fn_DeleteAnswer(AnsId);
                    return Json(new { issuccess = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { issuccess = false, message = "Something weent wrong. Try again." }, JsonRequestBehavior.AllowGet);
                }
            }

        }

        [HttpDelete]
        public JsonResult DeleteQuestion(int QueId)
        {
            using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
            {
                if (QueId > 0)
                {
                    var existsData = _dbcontext.tbl_question.Where(x => x.QueId == QueId).FirstOrDefault();
                    if (existsData == null)
                    {
                        return Json(new { issuccess = false, message = "Data not found. Try again." }, JsonRequestBehavior.AllowGet);
                    }

                    fn_DeleteAnswerByQueId(existsData.QueId);

                    _dbcontext.tbl_question.Remove(existsData);
                    _dbcontext.SaveChanges();
                    return Json(new { issuccess = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { issuccess = false, message = "Something weent wrong. Try again." }, JsonRequestBehavior.AllowGet);
                }
            }

        }

        private void fn_DeleteAnswerByQueId(int queId)
        {
            using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
            {
                var model = _dbcontext.tbl_question.Include("tbl_answer").Where(x => x.QueId == queId).FirstOrDefault();
               
                if(model.tbl_answer!=null || model.tbl_answer.Count > 0)
                {
                    foreach(var item in model.tbl_answer)
                    {
                        fn_DeleteAnswer(item.AnsId);
                    }
                }                 
            }
        }
        private void fn_DeleteAnswer(int ansId)

WhatToWhere/Areas/Web/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WhatToWhere.Models;
using WhereToWhere.Data;

namespace WhatToWhere.Areas.Web.Controllers
{
    public class RequestController : Controller
    {
        // GET: Web/Request
        public ActionResult Artist()
        {
            return View();
        }

        public ActionResult LoadData(DataTablesParam param)//(InwardRegisterModel model)
        {
            try
            {
                FilterOptions op = new FilterOptions();

                using (WhatToWhereDBEntities _dbcontext = new WhatToWhereDBEntities())
                {
                    var record = _dbcontext.tbl_user.OrderByDescending(x => x.UserId);
                    int TotalRecords = record.Count();

                    int pageNo = 1;
                    if (param.iDisplayStart >= param.iDisplayLength)
                    {
                        pageNo = (param.iDisplayStart / param.iDisplayLength) + 1;
                    }

                    var Data = record.Skip((pageNo - 1) * param.iDisplayLength).Take(param.iDisplayLength).ToList();

                    return Json(new
                    {
                        aaData = Data,
                        sEcho = param.sEcho,
                        iTotalDisplayRecords = (Data.Count > 0) ? TotalRecords : 0,
                        iTotalRecords = (Data.Count > 0) ? TotalRecords : 0

                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                // log4net.Error(ex);
                throw;
            }

        }
    }
}

WhatToWhere/Areas/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>WhatToWhere - @ViewBag.title</title>
    <link href="~/content/css/styles.css" rel="stylesheet" />
    <link href="~/content/css/custom.css" rel="stylesheet" />
    <script src="~/content/js/all.min.js"></script>
    <script src="~/content/js/jquery-3.5.1.slim.min.js"></script>
    <script src="~/content/js/bootstrap.bundle.min.js"></script>
    <script src="~/content/js/scripts.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css" />
</head>
<body class="sb-nav-fixed">

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">WhatToWhere - Admin</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="login.html">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action("Dashboard","Admin", new { Area = "web" })">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Users
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Active Users</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Blocked Users</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#request" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Request
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="request" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Artist","Request", new { Area = "web" })">New Artist</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#quiz" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Quiz
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="quiz" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Index","Quiz", new { Area = "web" })">List</a>
                            </nav>
                        </div>
                        @*<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            Pages
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                    Authentication
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="login.html">Login</a>
                        <a class="nav-link" href="register.html">Register</a>
                        <a class="nav-link" href="password.html">Forgot Password</a>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                    Error
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="401.html">401 Page</a>
                        <a class="nav-link" href="404.html">404 Page</a>
                        <a class="nav-link" href="500.html">500 Page</a>
                    </nav>
                </div>
            </nav>
        </div>*@
                        @*<div class="sb-sidenav-menu-heading">Addons</div>
        <a class="nav-link" href="charts.html">
            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
            Charts
        </a>
        <a class="nav-link" href="tables.html">
            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
            Tables
        </a>*@
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Administrator
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            @RenderBody()
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; whattowhere.com 2021</div>
                        @*<div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>*@
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <div class="overlay"></div>


    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>

    <!-- Jquery DataTable Plugin Js -->
    @*<script src="~/content/jquery-datatable/jquery.dataTables.js"></script>
        <script src="~/content/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
        <script src="~/content/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
        <script src="~/content/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
        <script src="~/content/jquery-datatable/extensions/export/jszip.min.js"></script>
        <script src="~/content/jquery-datatable/extensions/export/pdfmake.min.js"></script>
        <script src="~/content/jquery-datatable/extensions/export/vfs_fonts.js"></script>
        <script src="~/content/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
        <script src="~/content/jquery-datatable/extensions/export/buttons.print.min.js"></script>*@

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/datatables-demo.js"></script>*@
    <script>
        $(document).on({
            ajaxStart: function () {
                $("body").addClass("loading");
            },
            ajaxStop: function () {
                $("body").removeClass("loading");
            }
        });
    </script>
</body>
</html>

WhatToWhere/Areas/Web/Views/Shared/_Message.cshtml

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
}
@if (ViewBag.Success != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Success
    </div>
}